version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: mvn compile
      - snyk/scan:
         token-variable: API_TOKEN
         monitor-on-build: false
         project: 'mvnwebapp-1/circleci-project-setup-app'
workflows: null         
      
      
